version: "3.8"
services:
  mongodb:
    image: mongo:6
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ansh
      MONGO_INITDB_ROOT_PASSWORD: ansh
      MONGO_INITDB_DATABASE: productiondb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ansh
      ME_CONFIG_MONGODB_ADMINPASSWORD: ansh
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

volumes:
  mongo_data:
